import Header from "@/components/Header"
import { Poppins } from "next/font/google"

export const metadata = {
  title: "Practice Next.js 13",
  description: "Generated by Next.js",
  keywords: "web development, web design , javascript, Next, react",
}

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
