import Navbar from '@/components/Navbar';
import Providers from '@/components/Providers';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        // className={[inter.className, "relative h-full antialiased"]
        //   .filter(Boolean)
        //   .join(" ")}
        className={cn(
          inter.className,
          'relative h-full font-sans antialiased',
        )}
      >
        <Providers>
          <Navbar />
          <main className='relative flex flex-col min-h-screen'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}