import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(
    '[inter.className].filter(Boolean).join(" ") ',
    [inter.className].filter(Boolean).join(" ")
  );
  return (
    <html lang="en">
      <body
        // className={[inter.className, "relative h-full antialiased"]
        //   .filter(Boolean)
        //   .join(" ")}
        className={cn(inter.className, "relative h-full font-sans antialiased")}
      >
        <Navbar />
        <main className="relative flex flex-col min-h-screen">{children}</main>
      </body>
    </html>
  );
}